name: amd64
on:
  push:
    branches:
      - amd64-*
    tags:
      - release-amd64-*
  pull_request:
    branches:
      - amd64-*

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:13
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Print branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.base_ref }} (PR target)"
          else
            echo ${{ github.ref_name }}
          fi
      - name: Extract tini branch
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            REF=${{ github.base_ref }}
          else
            REF=${{ github.ref_name }}
          fi
          echo "REF=$REF"
          RAW_VERSION=$(echo $REF | awk -F'amd64-' '{print $2}')
          echo "RAW_VERSION=$RAW_VERSION"
          TINI_BRANCH=$(echo $RAW_VERSION | awk -F'+' '{print $1}')
          echo "TINI_BRANCH=$TINI_BRANCH"
          echo "TINI_BRANCH=$TINI_BRANCH" >> ${GITHUB_ENV}
          if echo "$RAW_VERSION" | grep -qE '[+].*(alpha|beta|rc)'; then
            IS_STABLE=false
          else
            IS_STABLE=true
          fi
          echo "IS_STABLE=$IS_STABLE"
          echo "IS_STABLE=$IS_STABLE" >> ${GITHUB_OUTPUT}
      - name: Clone tini
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: krallin/tini
          ref: ${{ env.TINI_BRANCH }}
          path: tini
      - name: ls
        run: ls -lah
      - name: Install build tools
        run: |
          apt update
          apt install -y git cmake make golang file
      #- name: Apply patches
      #  working-directory: tini
      #  run: git apply ../*.patch
      - name: Build tini
        working-directory: tini
        run: |
          cmake .
          make
      - name: Print binary SHA-256 checksums
        working-directory: tini
        run: |
          find tini -type f | xargs sha256sum
          find tini-static -type f | xargs sha256sum
      - name: Inspect binary file types
        working-directory: tini
        run: |
          echo "=== bin ==="
          file tini
          file tini-static
      - name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: tini-amd64-binaries
          path: |
            tini/tini
            tini/tini-static
